#! /usr/bin/env python

from __future__ import print_function
from npsolve import *

initiallize_material_index()
rel_rad_spheroid = [[0.8, 0.8], [0.2, 0.2]]
rad = [10.0, 10.0]
indx = [material_index("Ag"), material_index("Au")]

qext, qscat, qabs = npsolve(2, rad, rel_rad_spheroid, indx, 1.0, False, 1.0, 1.0, Efficiency)

print()
print()
print('THIS IS PTEST')
print()

f = 'NPSOLVE: Ext {0:.16f}, Sca {1:.16f}, Abs {2:.16}'
for i, (e, s, a) in enumerate(zip(qext, qscat, qabs)):
    print(f.format(e, s, a))
    if not i < 20:
        break
