#! /usr/bin/env python

from glob import glob
from os import remove
from os.path import join
from shutil import rmtree
from subprocess import call

# Make a list of what to delete
files = ('CMakeCache.txt', 'cmake_install.cmake', 'install_manifest.txt',
'Makefile', 'CTestTestfile.cmake', 'testNPSolve','verifyNPSolve', 'libfSolve.a')
dirs  = ('CMakeFiles', 'modules', 'lib', 'build', 'dist', 'NPSolve.framework',
         'npsolve.egg-info', 'ThirdParty', 'Testing', )

# Removes the cmake files
for f in files+tuple(glob('libNPSolve.*')+glob('*.pyc')):
    try:
        remove(f)
    except OSError:
        pass

# Removes the directories
for d in dirs:
    try:
        rmtree(d)
    except OSError:
        pass
