#! /usr/bin/env python

from glob import glob
from os import remove
from shutil import rmtree

# Make a list of what to delete
files = ('CMakeCache.txt', 'cmake_install.cmake', 'install_manifest.txt',
'Makefile',)
dirs  = ('CMakeFiles', 'modules', 'lib', 'build', 'dist', 'NPSolve.framework',)

# Removes the cmake files
for f in files+tuple(glob('libNPSolve.*')+glob('*.pyc')):
    try:
        remove(f)
    except OSError:
        pass

# Removes the directories
for d in dirs:
    try:
        rmtree(d)
    except OSError:
        pass
