#! /usr/bin/env python

from glob import glob
from os import remove, getcwd, walk
from os.path import join
from shutil import rmtree
from fnmatch import filter as ffilter

# Get all files in all directories
rmfiles = []
for d, dirs, files in walk(getcwd()):
    # Find the files to remove
    rmfiles.extend([join(d, f) for f in ffilter(files, "*.pyc")])

# Removes the cmake files
for f in rmfiles:
    try:
        remove(f)
    except OSError:
        pass

# Removes directories
for d in ['lib', 'dist', 'build', 'test']+glob('*.egg-info'):
    try:
        rmtree(d)
    except OSError:
        pass
